I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 221, in script
    if isEngineer:
  File "game/script.rpy", line 221, in <module>
    if isEngineer:
NameError: name 'isEngineer' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 221, in script
    if isEngineer:
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\ast.py", line 1647, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\python.py", line 1670, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Cedric\Documents\renpy-6.99.11-sdk\renpy\python.py", line 1665, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 221, in <module>
    if isEngineer:
NameError: name 'isEngineer' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Rutgers Love-iversity 1.0
